version: "3"
services:
  postgres:
    image: postgres
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: piyush
      POSTGRES_PASSWORD: piyush
      POSTGRES_DB: rust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
